### ISSUE TITLE
Setup Home Page

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#1]
Create a basic home page with navigation links to login and register pages.

**Comment by ParthDhavan04** [comment]
Hi, I would like to take up this issue.

**Comment by Saga690** [comment]
Assign this to me!

**Comment by Vaibhav-Rawat03** [comment]
Assigned to both

**Comment by iDream2** [comment]
Can this be assigned to me, as well ?

**Comment by ParthDhavan04** [comment]
Please Review my Pull Request.

**Comment by Vaibhav-Rawat03** [comment]
Parth check the comment in it

**Comment by Vaibhav-Rawat03** [comment]
assigned to idream2

guys the first commit will get the points

**Comment by Vaibhav-Rawat03** [comment]
Please use vite framework and check the discord for any confusions and updates
and do not push directly to main branch

**Comment by ParthDhavan04** [comment]
I used Vite Framework in it.Please Check the PR that i generated.
