### ISSUE TITLE
Patient Dashboard: Share Records with Doctors

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#11]
Implement functionality for patients to share their medical records with doctors.

**Comment by ParthDhavan04** [comment]
i want to work on this

**Comment by rampantvoid** [comment]
hi can you assign this to me

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by Saga690** [comment]
Would like to work on this
