### ISSUE TITLE
Refactor Index file

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#129]
Remove the schema and the routes from the index.js file and put them(update if needed) in the respective files

**Comment by Saga690** [comment]
Would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by shradiphylleia** [comment]
would like to work. will create controller routes  models

**Comment by Vaibhav-Rawat03** [comment]
assigned, but make changes to index rotues and schema only

> would like to work. will create controller routes models
