### ISSUE TITLE
Encrypt Medical Records in Database

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#13]
Implement encryption for storing medical records securely in the database.

**Comment by shradiphylleia** [comment]
would like to work on this.need to know the lib/algorithm to use to implement this issue

**Comment by Vaibhav-Rawat03** [comment]
it is completely your choice .

**Comment by shradiphylleia** [comment]
> it is completely your choice .

the data would be files/documents right? and not details entered by users manually e.g. details entered during login/signup

**Comment by Vaibhav-Rawat03** [comment]
The data is an image uploaded by patients and the doctor name etc, check the schema issue and then you will get idea.

**Comment by shradiphylleia** [comment]
pls assign.

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.

**Comment by Saga690** [comment]
Would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Assigned
