### ISSUE TITLE
Efficiency Improvement

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#131]
The browser console on scrolling the page prints a lot of repetitive and useless data . remove it from all pages

**Comment by Saga690** [comment]
Would like to work on this

**Comment by ParthDhavan04** [comment]
Would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by rampantvoid** [comment]
can you assign this to me

**Comment by Vaibhav-Rawat03** [comment]
Assigned to all
