### ISSUE TITLE
Create schema and store login for users 

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#14]
Create MongoDB schema and store login details in the database

**Comment by AbhishekJ24** [comment]
i would like to work on this, could you please provide with other relevant details for the same

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by nandiniiiiiiii** [comment]
I would like to work on this issue so can you kindly assign this to me. As I have worked with Mongo for the same.

**Comment by shradiphylleia** [comment]
i would like to take this up too if possible.

**Comment by Vaibhav-Rawat03** [comment]
Guys only one issue at a time will be assigned to you

**Comment by shradiphylleia** [comment]
> Guys only one issue at a time will be assigned to you
 was waorking on jwt so had to create the user model.I am pretty much done with it.Please let me know how to proceed with it

**Comment by Vaibhav-Rawat03** [comment]
you may proceed

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.
