### ISSUE TITLE
Frontend and backend improvement

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#145]
Merge NavDcotor and NavPatient in frontend,
use session instead of localstorage and axios to be used from navbar instead of request app.js

**Comment by Saga690** [comment]
Would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by ParthDhavan04** [comment]
Can i work on this?

**Comment by Vaibhav-Rawat03** [comment]
Assigned
