### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#156]
fix dashboard ui, make it responsive and change classnames to avoid conflicting css. Fix flex wrap, the doctors email section should not wrap the same way as other parts, and fix the form section so it is distinctly visible

**Comment by rampantvoid** [comment]
@Vaibhav-Rawat03 can you assign this to me

**Comment by Saga690** [comment]
Would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Assigned
