### ISSUE TITLE
UI + backend functionality 

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#158]
/doctor endpoint should be separate for see patients (in doctor dashboard) and see doctor (in patient dashbord) (i.e make the files different for both) and make the endpoints working the see patients should show all the patients who have given access to the doctor and the see doctor endpoint should show all the doctors who have access to the patients

**Comment by Vaibhav-Rawat03** [comment]
Currently there is only one endpoint for both view patient and view doctor 
They should be inseparate files 
Also make use of express session in the backend for any operation instead of the email from the client side

**Comment by ParthDhavan04** [comment]
i would like to work on this.

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by rampantvoid** [comment]
would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Parth has been already working on it and is about to complete this so i wouldnt want you to waste time @rampantvoid
