### ISSUE TITLE
Updating back-end 

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#169]
Remove localstorage from profile page and implement session storage, implement logout functionality to end session on logout. If fields like full name, age and gender aren't filled, display some message instead of keeping it blank

**Comment by Saga690** [comment]
Would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by rampantvoid** [comment]
would like to work on it

**Comment by rampantvoid** [comment]
@Vaibhav-Rawat03

**Comment by ParthDhavan04** [comment]
would like to work on this
