### ISSUE TITLE
Create a navbar

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#17]
Create navbar for all pages

**Comment by ParthDhavan04** [comment]
I want to work on this.Can you provide me the UI?

**Comment by Vaibhav-Rawat03** [comment]
It has been create but you have to modify it
ill prvide the ui in the discord channel

**Comment by ParthDhavan04** [comment]
Please provide me the UI for navbar.

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.
