### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#177]
Remove localstorage from the project as a whole, use session storage wherever there is localstorage. Cleanup the backend, remove useless endpoints and also remove duplicate endpoints

**Comment by rampantvoid** [comment]
would like to work on it

**Comment by Saga690** [comment]
would like to work on it

**Comment by Vaibhav-Rawat03** [comment]
Assigned
