### ISSUE TITLE
Setup Login Page

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#2]
Create a login page with email and password fields.
Also integrate it with the backend endpoint(check the backend folder or ping me on discord)
The UI is available on discord

**Comment by VanshBhatia2192** [comment]
Hey, I would like to take up this issue.

**Comment by ParthDhavan04** [comment]
Hi, I would like to take up the issue.

**Comment by Saga690** [comment]
I would like to work on the issue

**Comment by Vaibhav-Rawat03** [comment]
assigned to vansh

**Comment by aryanrana19** [comment]
I would like to work on this issue

**Comment by iDream2** [comment]
Hi, I would like to work on this issue. I have had experience working with React and have worked on MERN as part of my minor project.

**Comment by Vaibhav-Rawat03** [comment]
assigned to aryan rana

**Comment by Vaibhav-Rawat03** [comment]
The login page should have 2 fields email and password

**Comment by Supragya1** [comment]
Hi! I Iike to contribute on this issue.
