### ISSUE TITLE
create schema in mongoDB for storing patient data

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#22]
create schema in mongoDB for Storing medical record (image) , username , date of upload , doctor name

**Comment by rampantvoid** [comment]
can you assign this issue to me

**Comment by Vaibhav-Rawat03** [comment]
Assigned to you

**Comment by Tacenda01** [comment]
hello!! I would also like to do this work.

**Comment by Vaibhav-Rawat03** [comment]
Assigned 
Whoever commits first will get the points

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.

**Comment by Vaibhav-Rawat03** [comment]
Only one issue will be assigned at once

**Comment by Saga690** [comment]
Would like to work on this
