### ISSUE TITLE
Integrate Frontend and backend

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#25]
Integrate login and signup pages with the backend (make sure to using tokens)

**Comment by ParthDhavan04** [comment]
I want to do this but login and sign up pages are not done yet.So how can i approach this?

**Comment by Vaibhav-Rawat03** [comment]
Yea so we will have to wait till the login and signup pages are created

**Comment by Vaibhav-Rawat03** [comment]
Assigned
