### ISSUE TITLE
Connect backend to mongoDB 

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#26]
Connection string is given in discord channel of health-reserve

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by Saga690** [comment]
Would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Assigned
