### ISSUE TITLE
Setup Register Page

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#3]
Create a registration page with fields for name, email, password, verify password, and role selection (patient/doctor).
Also integrate it with the backend endpoint(check the backend folder or ping me on discord)
The UI is available on discord

**Comment by ParthDhavan04** [comment]
Hi, I would like to take up this issue.

**Comment by Saga690** [comment]
I would like to work on the issue

**Comment by iDream2** [comment]
Hi, I would like to work on this issue. I have had experience working with React and have good experience with form handling.

**Comment by Vaibhav-Rawat03** [comment]
Assigned to Saga690

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.
