### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#32]
Design logo for Health-Reserve and put it in the public folder(it may be an image or anything that will be used in every other page)

**Comment by shradiphylleia** [comment]
i would like to work on this please see if this sample works so i can add it to the public folder.
Made using Canva
![Medical Care](https://github.com/upes-open/OSoC-24-Health-Reserve/assets/118170804/4b3a00be-dc36-4bc7-b976-523c423ed337)

**Comment by Vaibhav-Rawat03** [comment]
Shraddha pls contact me on the discord channel workspace for health-reserve
