### ISSUE TITLE
Patient Dashboard: Upload Medical Records

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#4]
Implement a form for patients to upload medical records.

**Comment by iDream2** [comment]
Assign this to me, please ! I have had experience in working with React and can handle form submission. But I do have a question - Will we just store the details in state Variables? Or is their any API where we can POST the records ?

**Comment by Vaibhav-Rawat03** [comment]
It will be an image upload .
use REST API(POST)
the endpoint should be /upload_record

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.

**Comment by Vaibhav-Rawat03** [comment]
Assigned

**Comment by ParthDhavan04** [comment]
I would like to work on this.

**Comment by Vaibhav-Rawat03** [comment]
Parth and Supragya are on this already

**Comment by Vaibhav-Rawat03** [comment]
Go ahead IDream 
the first commit gets the points
