### ISSUE TITLE
Fix UI

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#46]
Fix Ui of registration page make a patient and doctor button if doctor button is clicked a new filed license appears in which doctor can input their license number.
Remove the Empty space between the form and the footer of the registration page
Remove the left right scroll from Registration and login page

**Comment by Saga690** [comment]
Would like to contribute to this

**Comment by Vaibhav-Rawat03** [comment]
Assigned
