### ISSUE TITLE
Patient Dashboard: View Medical Records

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#5]
Implement a view for patients to see their uploaded medical records

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.

**Comment by ParthDhavan04** [comment]
I would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Assigned to both

**Comment by Saga690** [comment]
I would like to work on this

**Comment by Vaibhav-Rawat03** [comment]
Assigned to you
