### ISSUE TITLE
Patient Dashboard: Manage Medical Records

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#6]
Implement functionality to edit or delete uploaded medical records. also implement the same in backend for this

**Comment by ParthDhavan04** [comment]
I would like to take up this issue

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.

**Comment by Vaibhav-Rawat03** [comment]
Assigned to both

**Comment by rampantvoid** [comment]
hi i would like to work on thi
