### ISSUE TITLE
Doctor Dashboard: View Patient Records

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#7]
Implement a view for doctors to see authorized patient records. also change the backend for the same.

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.

**Comment by ParthDhavan04** [comment]
I want to work on this

**Comment by Vaibhav-Rawat03** [comment]
Guys you both have multiple so i wont be assigning to you currently

**Comment by ParthDhavan04** [comment]
Can i work on this issue?

**Comment by Vaibhav-Rawat03** [comment]
Assigned
