### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#8]
Create a profile page where users can view and update their personal information.

**Comment by the25thjin** [comment]
i would like to work on this issue

**Comment by Vaibhav-Rawat03** [comment]
assigned

**Comment by the25thjin** [comment]
@Vaibhav-Rawat03 
 is there any design for the profile page . if yes kindly provide

**Comment by the25thjin** [comment]
also can i use tailwind css or i have to use normal css?

**Comment by iDream2** [comment]
Hey I would like to work on this issue. I have had experience in React and would like to contribute to this,

**Comment by Vaibhav-Rawat03** [comment]
Please use vanilla css

**Comment by Vaibhav-Rawat03** [comment]
Assigned to IDream2

Whoever does the first commit will get the points

**Comment by Vaibhav-Rawat03** [comment]
Guys any template for ui is fine 
try to make it look like it is for a medical record

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.

**Comment by Vaibhav-Rawat03** [comment]
Assigned
