### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by Vaibhav-Rawat03** [upes-open/OSoC-24-Health-Reserve#9]
Create a settings page for users to manage their account settings.

**Comment by rishabh-108272** [comment]
Hi, I would like to work in this issue.

**Comment by Vaibhav-Rawat03** [comment]
assigned

**Comment by rishabh-108272** [comment]
Hi, can you please elaborate in detail what options and features can be added in account settings?

**Comment by Vaibhav-Rawat03** [comment]
Signout button, View profile button(redirecting to profile page) , change password , change username

**Comment by Supragya1** [comment]
Hi! I would Iike to contribute on this issue.

**Comment by Vaibhav-Rawat03** [comment]
This has been merged with Profile page
